# Generated by Django 2.2 on 2021-04-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200, verbose_name='Tag')),
                ('tag_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Tag',
            },
        ),
    ]
