# Generated by Django 2.2 on 2021-04-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_bank', '0002_auto_20210411_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
